%fbcca method filters the signal X into n subbands
%between the Wn(1) and Wn(2), then computes n CCA calculations
%using the specified method of band dvisition.

%&param X: this should be the raw EEG signal of channels x samples, it
%should have the same number of sameples as the reference Y

%&param Y: the reference signal generated by refsig function, it should
%have the same number of samples as signal X

%&param Wn, 1X2 array, of the bandpass filter used for the decoder

%&param N, number of bands to be cut into for FBCCA, minimum is 1

%&param Fs, sampling frequency 256 is what we used

%&method, can be one of three following method, 'm1','m3'
% m1:                           m3:
%        ----                             ----
%    ----                             --------
%----                             ------------

%maybe i will add the method m2 as well lol

function R = fbcca(X,Y,Wn,N,Fs)
    step_size = (Wn(2)-Wn(1))/N;
    Rp = 1;
    R = 0; 
    
    % these two need to be tuned to check performance
    a = 1.5;
    b = 0.25;
    n = 6;
    
    for fb=1:N
        Wp = [Wn(1)+(fb-1)*step_size Wn(2)]/(Fs/2);
        [num,den] = cheby1(n,Rp,Wp,'bandpass');
        XX = filtfilt(num,den,X.');
        [~,~,r]=cca(XX.',Y);
        rr=max(r);
        w=fb^(-a)+b;
        R=R+w*rr^2;
    end
    
end




